In [16]:
!pip install -i https://test.pypi.org/simple/ debentures-dot-com==0.1.1

Looking in indexes: https://test.pypi.org/simple/
Requirement already satisfied: debentures-dot-com==0.1.1 in d:\projects\debentures_dot_com\.venv\lib\site-packages (0.1.1)
Requirement already satisfied: requests in d:\projects\debentures_dot_com\.venv\lib\site-packages (from debentures-dot-com==0.1.1) (2.32.4)
Requirement already satisfied: pandas in d:\projects\debentures_dot_com\.venv\lib\site-packages (from debentures-dot-com==0.1.1) (2.3.1)
Requirement already satisfied: beautifulsoup4 in d:\projects\debentures_dot_com\.venv\lib\site-packages (from debentures-dot-com==0.1.1) (4.13.4)
Requirement already satisfied: python-dateutil in d:\projects\debentures_dot_com\.venv\lib\site-packages (from debentures-dot-com==0.1.1) (2.9.0.post0)
Requirement already satisfied: soupsieve>1.2 in d:\projects\debentures_dot_com\.venv\lib\site-packages (from beautifulsoup4->debentures-dot-com==0.1.1) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in d:\projects\debentures_dot_com\.venv\lib\site-packages (from beautifulsoup4->debentures-dot-com==0.1.1) (4.14.1)
Requirement already satisfied: numpy>=1.26.0 in d:\projects\debentures_dot_com\.venv\lib\site-packages (from pandas->debentures-dot-com==0.1.1) (2.3.1)
Requirement already satisfied: pytz>=2020.1 in d:\projects\debentures_dot_com\.venv\lib\site-packages (from pandas->debentures-dot-com==0.1.1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\projects\debentures_dot_com\.venv\lib\site-packages (from pandas->debentures-dot-com==0.1.1) (2025.2)
Requirement already satisfied: six>=1.5 in d:\projects\debentures_dot_com\.venv\lib\site-packages (from python-dateutil->debentures-dot-com==0.1.1) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\projects\debentures_dot_com\.venv\lib\site-packages (from requests->debentures-dot-com==0.1.1) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in d:\projects\debentures_dot_com\.venv\lib\site-packages (from requests->debentures-dot-com==0.1.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\projects\debentures_dot_com\.venv\lib\site-packages (from requests->debentures-dot-com==0.1.1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\projects\debentures_dot_com\.venv\lib\site-packages (from requests->debentures-dot-com==0.1.1) (2025.6.15)

In [17]:
from debentures_dot_com import EmissoesDebentures

In [18]:
ed = EmissoesDebentures()
ed.lista_deb_publicas().head()

d:\projects\debentures_dot_com\.venv\Lib\site-packages\debentures_dot_com\emissoes.py:18: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 18 of the file d:\projects\debentures_dot_com\.venv\Lib\site-packages\debentures_dot_com\emissoes.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(r.text)

    Ativo                                         Emissor    Situacao
0  AAJR11                   FILADELFIA SECURITIZADORA S/A  Registrado
1  AALM12                       AURA ALMAS MINERACAO S.A.  Registrado
2  AALR13             ALLIANCA SAUDE E PARTICIPACOES S.A.  Registrado
3  AARJA2  AQUA-RIO AQUARIO MARINHO DO RIO DE JANEIRO S/A  Registrado
4  ABFR12           ALCOESTE BIOENERGIA FERNANDOPOLIS S A  Registrado

In [19]:
ed.lista_caracteristicas('AAJR11').head(2)

         Descricao                        Valores
0  Codigo do Ativo                     AAJR11
1  Empresa          FILADELFIA SECURITIZADORA S/A

In [20]:
ed.pu_historico('AAJR11').head(2)

,Data do PU,Ativo,Valor Nominal,Juros,Pręmio,Preço Unitário,Critério de Cálculo,Situaçăo,
0,25/07/2025,AAJR11,"1.000,000000","13,151495",-,"1.013,151495",Padrăo - SND,Reg.,
1,24/07/2025,AAJR11,"1.000,000000","12,455015",-,"1.012,455015",Padrăo - SND,Reg.,

In [21]:
from debentures_dot_com import MercadoSecundario
ms = MercadoSecundario()
ms.arquivo_precos_diario('20250717').head(2)

                                                                                                                                                                                                                                                    raw
Código Nome                          Repac./  Venc. Índice/ Correção Taxa de Compra Taxa de Venda Taxa Indicativa Desvio Padrão Intervalo Indicativo Minimo Intervalo Indicativo Máximo PU          % PU Par / % VNE Duration % Reune  Referência NTN-B
AALM12 AURA ALMAS MINERACAO S.A. (*) 02/10/2030     DI + 1,6%        1,25           0,9695        1,1118          0,019         1,0928                      1,1308                      1058,481878 101,3565         706,15   NaN                   NaN